AWSTemplateFormatVersion: '2010-09-09'
Description: 'This stack creates a lambda and an apigateway endpoint to process security scan results.'

Parameters:
  PipelineName:
    Type: String
    Description:  The name of the pipeline that will be created.  Used here to help lock down permissions instead of using wildcards.

Resources:

  WebhookUrl:
    Type: AWS::SSM::Parameter
    DependsOn: ApiGateway
    Properties:
      Name: /pipeline/example/trendmicro/dssc/webhook
      Type: String
      Value: !Sub  https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev
      Description: DSSC Webhook Url

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}
      Description: Example API for Trend Micro DSSC Webhook

  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt WebhookLambda.Arn
      ResourceId: !GetAtt ApiGateway.RootResourceId
      RestApiId: !Ref ApiGateway

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayRootMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: dev

  WebhookLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Description: Example Lambda for Trend Micro DSSC Webhook
      FunctionName: !Sub ${AWS::StackName}
      Timeout: 60
      Environment:
        Variables:
          DSSC_SECRET: '{{resolve:ssm:/pipeline/example/trendmicro/dssc/secret:1}}'
      Code:
        ZipFile: |-
          import json
          import boto3
          import os
          import logging
          import hmac
          import hashlib

          CLIENT = boto3.client('codepipeline')
          LOGGER = logging.getLogger()
          LOGGER.setLevel(logging.INFO)

          def is_from_tmdssc(body, signature):
            message = bytes(body, 'utf-8')
            secret = bytes(os.environ['DSSC_SECRET'], 'utf-8')

            actual = hmac.new(secret, message, digestmod=hashlib.sha256).hexdigest()

            return hmac.compare_digest(signature, actual)

          def lambda_handler(event, context):
            body = event['body'].replace('\"', '"')
            signature = event['headers']['X-Scan-Event-Signature']

            if is_from_tmdssc(body, signature):

              payload = json.loads(event['body'])
              pipeline_execution_id = payload['scan']['context']['pipeline_execution_id']
              pipeline_name = payload['scan']['context']['pipeline_name']
              stage_name = 'ApproveDeployment'
              action_name = 'SecurityScanApproval'
              critical_errors_threshold = os.environ.get('CRITICAL_ERRORS_THRESHOLD') or 0
              high_errors_threshold = os.environ.get('HIGH_ERRORS_THRESHOLD') or 5

              pipeline_state = CLIENT.get_pipeline_state(
                name = pipeline_name
              )

              token = None
              for state in pipeline_state['stageStates']:
                if state['stageName'] == stage_name:
                  for action in state['actionStates']:
                    if action['actionName'] == action_name and action['latestExecution']['status'] == 'InProgress':
                      token = action['latestExecution']['token']
                      break
                  break

              if token:

                findings = payload['scan']['findings']['vulnerabilities']['total']
                view_url = f"{payload['scan']['context']['dssc_url']}/scans/{payload['scan']['id']}"
                status = None

                if findings['critical'] > int(critical_errors_threshold) or findings['high'] > int(high_errors_threshold):
                  status = 'Rejected'
                  summary = f"There are {findings['critical']} critical issues and {findings['high']} high issues detected. Full results available at {view_url}"
                else:
                  status = 'Approved'
                  summary = f'Full results available at {view_url}'

                CLIENT.put_approval_result(
                  pipelineName = pipeline_name,
                  stageName = stage_name,
                  actionName = action_name,
                  result = {
                    'summary': summary,
                    'status': status
                  },
                  token = token
                )
                LOGGER.info(f'Pipeline {pipeline_name} execution id {pipeline_execution_id} status set to \'{status}\'.')
              else:
                LOGGER.info(f'It appears that {pipeline_name} execution {pipeline_execution_id} is no longer InProgress so there is nothing to Approve/Reject.')

              return {
                  'statusCode': 204,
                  'body': None
              }
            else:
              LOGGER.error(f'Calculated signature of event body received does not match the signature provided from DSSC!')
              return {
                  'statusCode': 401,
                  'body': None
              }

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: trendmicro-lambda-webhook
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action: codepipeline:*
                Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*

  LambdaApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WebhookLambda.Arn
      Principal: apigateway.amazonaws.com
